In [22]:
from imblearn.over_sampling import SMOTE
from sklearn.datasets import make_classification
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import numpy as np
from random import randint

In [23]:
data1=pd.read_csv('vitals_data .csv')
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PatientID           39 non-null     int64
 1   Age                 39 non-null     int64
 2   Sex                 39 non-null     object
 3   Height              39 non-null     int64
 4   Weight              39 non-null     int64
 5   Prior_BP_issues     39 non-null     object
 6   Prior_heart_issues  39 non-null     object
 7   Prior_resp_issues   39 non-null     object
 8   Heartrate           39 non-null     int64
 9   Spo2                39 non-null     int64
 10  Overdose            39 non-null     object
dtypes: int64(6), object(5)
memory usage: 3.5+ KB

In [24]:
data1.head()

,PatientID,Age,Sex,Height,Weight,Prior_BP_issues,Prior_heart_issues,Prior_resp_issues,Heartrate,Spo2,Overdose
0,39,27,M,162,116,No,No,No,53,91,Yes
1,35,35,M,189,104,No,Yes,Yes,68,87,No
2,34,39,M,169,93,No,No,No,72,98,No
3,33,23,M,174,50,No,No,No,54,90,Yes
4,32,21,M,172,109,No,No,Yes,68,70,No

In [25]:
def get_categorical_and_numeric_columns(df):
    categorical_columns = []
    numeric_columns = []

    for column in df.columns:
        if df[column].dtype == 'object' or pd.api.types.is_categorical_dtype(df[column].dtype):
            categorical_columns.append(column)
        elif column != 'Target':
            numeric_columns.append(column)

    return categorical_columns, numeric_columns


categorical_columns, numeric_columns  = get_categorical_and_numeric_columns(data1)
categorical_columns, numeric_columns

(['Sex',
  'Prior_BP_issues',
  'Prior_heart_issues',
  'Prior_resp_issues',
  'Overdose'],
 ['PatientID', 'Age', 'Height', 'Weight', 'Heartrate', 'Spo2'])

In [5]:
# from sklearn.preprocessing import LabelEncoder
# label_encoder = LabelEncoder()

# for column in categorical_columns:
#     data1[column] = label_encoder.fit_transform(data1[column])
    
# data1

,PatientID,Age,Sex,Height,Weight,Prior_BP_issues,Prior_heart_issues,Prior_resp_issues,Heartrate,Spo2,Overdose
0,39,27,1,162,116,0,0,0,53,91,1
1,35,35,1,189,104,0,1,1,68,87,0
2,34,39,1,169,93,0,0,0,72,98,0
3,33,23,1,174,50,0,0,0,54,90,1
4,32,21,1,172,109,0,0,1,68,70,0
5,31,42,1,184,111,0,0,0,80,99,0
6,30,47,1,186,116,1,0,1,76,97,0
7,29,31,1,163,74,0,0,0,75,99,0
8,28,57,1,176,73,1,1,0,78,98,0
9,27,22,1,190,92,0,0,0,52,90,1
10,26,19,1,178,69,0,0,0,54,91,1
11,25,33,1,187,86,0,1,1,78,99,0
12,24,32,1,183,90,0,0,0,51,89,1
13,23,24,1,172,103,0,0,0,50,88,1
14,22,21,1,175,110,0,0,0,85,99,0
15,21,23,1,181,69,0,0,1,90,93,0
16,20,28,1,171,96,0,0,0,78,90,1
17,19,20,1,184,89,0,0,0,79,96,0
18,18,44,1,176,88,0,0,0,50,91,1
19,17,53,1,179,58,1,0,1,62,96,0
20,16,27,0,164,65,0,0,0,79,99,0
21,15,35,0,165,75,0,1,0,57,95,0
22,14,39,0,163,68,0,0,1,63,93,0
23,13,23,0,176,85,0,0,0,51,90,1
24,12,21,0,152,47,0,0,0,61,96,0
25,11,42,0,172,78,1,0,0,54,89,1
26,10,47,0,178,48,1,1,0,52,98,0
27,9,31,0,160,69,0,0,1,80,90,0
28,8,26,0,174,85,0,0,0,82,99,0
29,7,22,0,161,65,0,0,0,79,98,0
30,6,19,0,174,88,0,0,0,69,97,0
31,5,33,0,166,80,0,0,0,52,88,1
32,4,32,0,156,72,0,0,0,78,99,0
33,3,24,0,170,82,0,0,1,72,93,0
34,2,21,0,150,57,0,0,0,73,97,0
35,1,23,0,175,59,0,0,0,53,90,1
36,36,28,0,166,58,0,0,0,82,98,0
37,37,20,0,155,78,0,0,1,78,87,0
38,38,44,0,151,46,1,0,0,49,86,1

In [26]:
from sdv.datasets.local import load_csvs
data = load_csvs(folder_name='/Users/yatingoyal/Desktop/capstoneml/')

/Users/yatingoyal/anaconda3/lib/python3.10/site-packages/sdv/datasets/local.py:34: UserWarning: Ignoring incompatible files ['.DS_Store', 'ana.ipynb'] in folder '/Users/yatingoyal/Desktop/capstoneml/'.
  warnings.warn(

In [27]:
data.keys()

dict_keys(['vitals_data '])

In [10]:
vitals_table = data['vitals_data ']

In [11]:
vitals_table.head()

,PatientID,Age,Sex,Height,Weight,Prior_BP_issues,Prior_heart_issues,Prior_resp_issues,Heartrate,Spo2,Overdose
0,39,27,M,162,116,No,No,No,53,91,Yes
1,35,35,M,189,104,No,Yes,Yes,68,87,No
2,34,39,M,169,93,No,No,No,72,98,No
3,33,23,M,174,50,No,No,No,54,90,Yes
4,32,21,M,172,109,No,No,Yes,68,70,No

In [19]:
from sdv.datasets.local import load_csvs
from sdv.datasets.demo import download_demo
data = load_csvs(folder_name='/Users/yatingoyal/Desktop/capstoneml/')

/Users/yatingoyal/anaconda3/lib/python3.10/site-packages/sdv/datasets/local.py:34: UserWarning: Ignoring incompatible files ['.DS_Store', 'ana.ipynb'] in folder '/Users/yatingoyal/Desktop/capstoneml/'.
  warnings.warn(

In [31]:
from sdv.metadata import SingleTableMetadata

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data=data1)

In [32]:
print('Auto detected data:\n')
metadata

Auto detected data:

{
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1",
    "primary_key": "PatientID",
    "columns": {
        "PatientID": {
            "sdtype": "id"
        },
        "Age": {
            "sdtype": "numerical"
        },
        "Sex": {
            "sdtype": "categorical"
        },
        "Height": {
            "sdtype": "numerical"
        },
        "Weight": {
            "sdtype": "numerical"
        },
        "Prior_BP_issues": {
            "sdtype": "categorical"
        },
        "Prior_heart_issues": {
            "sdtype": "categorical"
        },
        "Prior_resp_issues": {
            "sdtype": "categorical"
        },
        "Heartrate": {
            "sdtype": "numerical"
        },
        "Spo2": {
            "sdtype": "numerical"
        },
        "Overdose": {
            "sdtype": "categorical"
        }
    }
}

In [33]:
from sdv.single_table import GaussianCopulaSynthesizer

synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(data1)

In [37]:
synthetic_data = synthesizer.sample(num_rows=4041)
synthetic_data

,PatientID,Age,Sex,Height,Weight,Prior_BP_issues,Prior_heart_issues,Prior_resp_issues,Heartrate,Spo2,Overdose
0,5000,30,F,174,87,No,No,No,68,97,No
1,5001,29,M,182,96,No,No,No,58,98,No
2,5002,25,M,184,75,No,Yes,No,49,94,No
3,5003,20,M,187,112,No,No,Yes,82,96,No
4,5004,28,F,153,46,No,No,No,57,97,No
...,...,...,...,...,...,...,...,...,...,...,...
4036,9036,33,F,188,65,No,Yes,Yes,85,96,Yes
4037,9037,41,F,156,50,No,No,No,78,98,No
4038,9038,32,F,153,53,No,No,No,61,93,No
4039,9039,29,M,159,61,No,No,Yes,52,89,Yes
4040,9040,24,F,178,101,Yes,No,Yes,87,96,No

In [40]:


# Save the DataFrame to a CSV file
synthetic_data.to_csv('output.csv', index=False)